name: Build and Deploy to ECR

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to AWS ECR
      run: |
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 328927860119.dkr.ecr.us-east-1.amazonaws.com
      env:
        AWS_DEFAULT_REGION: us-east-1

    - name: Build and Push Docker Image
      run: |
        docker build -t serverless-cicd:latest .
        docker tag serverless-cicd:latest 328927860119.dkr.ecr.us-east-1.amazonaws.com/serverless-cicd:latest
        docker push 328927860119.dkr.ecr.us-east-1.amazonaws.com/serverless-cicd:latest

    - name: Create Image Definitions JSON File
      run: echo '[{"name": "serverless-web", "imageUri":"328927860119.dkr.ecr.us-east-1.amazonaws.com/serverless-cicd:latest"}]' > imagedefinitions.json

    - name: Upload Image Definitions as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: imagedefinitions
        path: imagedefinitions.json
